### PR TITLE
Release fast lane

### PR DESCRIPTION
**Pull request by bitionaire**
* Added preperation for maven central release
* Refactored bits of code
* Added example server implementation
* Added (some kind of) HATEOAS links
* Added links from root resource `'/'`
* Fixed issues & Added tests

### CODE REVIEW

**Comment by piranha87** [comment]
LGTM

**Comment by piranha87** [comment]
:+1:

**Comment by piranha87** [comment]
:+1:

**Comment by bitionaire** [comment]
Resolved [Paging links issue](https://github.com/1and1/concierge/issues/8)

**Comment by piranha87** [comment]
LGTM

**Comment by netdevfighter** [comment]
:+1:

**Pull request merged**
